-- 판매자 테이블
CREATE TABLE IF NOT EXISTS sellers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id TEXT UNIQUE,
    company_name TEXT UNIQUE,
    representative_name TEXT,
    business_registration_number TEXT,
    business_address TEXT,
    email TEXT,
    phone TEXT,
    mail_order_number TEXT,
    satisfaction_score INTEGER,
    review_count INTEGER,
    total_product_count INTEGER,
    is_abusing_seller BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 상품 테이블
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT UNIQUE,
    vendor_name TEXT REFERENCES sellers(company_name) ON DELETE CASCADE,
    name TEXT,
    item_id TEXT,
    review_count INTEGER,
    price INTEGER,
    original_price INTEGER,
    candidate_price INTEGER,
    discount_rate INTEGER,
    is_seller_rocket BOOLEAN,
    product_rating FLOAT,
    category TEXT,
    shipping_fee INTEGER,
    shipping_days INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 리뷰 테이블
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT REFERENCES products(product_id) ON DELETE CASCADE,
    review_date TEXT,
    review_title TEXT,
    review_text TEXT,
    review_rating INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(product_id, review_date, review_rating)
);

-- 문의 테이블
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT REFERENCES products(product_id) ON DELETE CASCADE,
    question_date TEXT,
    question TEXT,
    answer_date TEXT,
    answer TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(product_id, question_date, question)
);
