-- 판매자(sellers) 테이블
CREATE TABLE IF NOT EXISTS sellers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id TEXT,
    company_name TEXT UNIQUE,
    representative_name TEXT,
    business_registration_number TEXT,
    business_address TEXT,
    email TEXT,
    phone TEXT,
    mail_order_number TEXT,
    satisfaction_score INTEGER,
    review_count INTEGER,
    total_product_count INTEGER,
    is_abusing_seller BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 상품(products) 테이블
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT UNIQUE,
    vendor_name TEXT REFERENCES sellers(company_name) ON DELETE CASCADE,
    name TEXT,
    item_id TEXT,
    review_count INTEGER,
    price INTEGER,
    original_price INTEGER,
    candidate_price INTEGER,
    discount_rate INTEGER,
    product_rating INTEGER,
    rating_5 INTEGER DEFAULT 0,
    rating_4 INTEGER DEFAULT 0,
    rating_3 INTEGER DEFAULT 0,
    rating_2 INTEGER DEFAULT 0,
    rating_1 INTEGER DEFAULT 0,
    category TEXT,
    shipping_fee INTEGER,
    shipping_days INTEGER,
    inquiry_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 리뷰(reviews) 테이블
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT REFERENCES products(product_id) ON DELETE CASCADE,
    review_date TEXT,
    review_title TEXT,
    review_text TEXT,
    review_rating INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(product_id, review_date, review_rating)
);

-- 상품문의(questions) 테이블
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT REFERENCES products(product_id) ON DELETE CASCADE,
    question_date TEXT,
    question TEXT,
    answer_date TEXT,
    answer TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(product_id, question_date, question)
);
